services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    env_file:
     - app.env
    environment:
      MYSQL_ROOT_PASSWORD: viva#1919
      MYSQL_DATABASE: demodb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql_scripts:/docker-entrypoint-initdb.d

  # redis:
  #   image: redis:7.0.10
  #   container_name: redis
  #   restart: always
  #   env_file:
  #     - prod.env
  #   ports:
  #     - "6379:6379"
      
  book-store:
    build: .
    container_name: book-store
    ports:
      - "9011:9011"
    env_file:
      - app.env
    depends_on:
      - mysql
      # - redis
    links:
      - mysql
      # - redis

volumes:
  db_data: